### ISSUE TITLE
Docker invalid reference format

### ISSUE THREAD

**Issue by BenjaminEngeset** [TheCloudTheory/arm-estimator#214] opened 2023-11-02 12:57 UTC
Just converted from Azure DevOps to GitHub Actions and I'm currently facing this issue. Windows-2022 runner.

The step looks like this.

```yml
 - name: Cost estimate
   if: ${{ steps.get-target-scope.outputs.target_scope == 'resourceGroup' }}
   run: docker run -v $(pwd)/modules:/app/modules thecloudtheory/azure-cost-estimator:latest ${{ steps.get-test-file.outputs.test_file_path }} ${{ secrets.AZURE_SUBSCRIPTION_ID_T_PLATFORM_001 }} ${{ steps.create-test-resource-group.outputs.rg_name }} -e AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }} -e AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID_BRM_DEPLOYMENT_TEST_RG_003 }} -e AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET_BRM_DEPLOYMENT_TEST_RG_003 }}
```
```
##[debug]Evaluating condition for step: 'Cost estimate'
##[debug]Evaluating: (success() && (steps.get-target-scope.outputs.target_scope == 'resourceGroup'))
##[debug]Evaluating And:
##[debug]..Evaluating success:
##[debug]..=> true
##[debug]..Evaluating Equal:
##[debug]....Evaluating Index:
##[debug]......Evaluating Index:
##[debug]........Evaluating Index:
##[debug]..........Evaluating steps:
##[debug]..........=> Object
##[debug]..........Evaluating String:
##[debug]..........=> 'get-target-scope'
##[debug]........=> Object
##[debug]........Evaluating String:
##[debug]........=> 'outputs'
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'target_scope'
##[debug]....=> 'resourceGroup'
##[debug]....Evaluating String:
##[debug]....=> 'resourceGroup'
##[debug]..=> true
##[debug]=> true
##[debug]Expanded: (true && ('resourceGroup' == 'resourceGroup'))
##[debug]Result: true
##[debug]Starting: Cost estimate
##[debug]Loading inputs
##[debug]Evaluating: format('docker run -v $(pwd)/modules:/app/modules thecloudtheory/azure-cost-estimator:latest {0} {1} {[2](https://github.com/xxx/bicep-registry-modules-test/actions/runs/6732626593/job/18299980260#step:8:2)} -e AZURE_TENANT_ID={[3](https://github.com/xxx/bicep-registry-modules-test/actions/runs/6732626593/job/18299980260#step:8:3)} -e AZURE_CLIENT_ID={[4](https://github.com/xxx/bicep-registry-modules-test/actions/runs/6732626593/job/18299980260#step:8:4)} -e AZURE_CLIENT_SECRET={[5](https://github.com/xxx/bicep-registry-modules-test/actions/runs/6732626593/job/18299980260#step:8:5)}', steps.get-test-file.outputs.test_file_path, secrets.AZURE_SUBSCRIPTION_ID_T_PLATFORM_001, steps.create-test-resource-group.outputs.rg_name, secrets.AZURE_TENANT_ID, secrets.AZURE_CLIENT_ID_BRM_DEPLOYMENT_TEST_RG_003, secrets.AZURE_CLIENT_SECRET_BRM_DEPLOYMENT_TEST_RG_003)
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> 'docker run -v $(pwd)/modules:/app/modules thecloudtheory/azure-cost-estimator:latest {0} {1} {2} -e AZURE_TENANT_ID={3} -e AZURE_CLIENT_ID={4} -e AZURE_CLIENT_SECRET={5}'
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating Index:
##[debug]........Evaluating steps:
##[debug]........=> Object
##[debug]........Evaluating String:
##[debug]........=> 'get-test-file'
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'outputs'
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'test_file_path'
##[debug]..=> 'modules\containerregistry\registries\test\main.test.bicep'
##[debug]..Evaluating Index:
##[debug]....Evaluating secrets:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'AZURE_SUBSCRIPTION_ID_T_PLATFORM_001'
##[debug]..=> '***'
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating Index:
##[debug]........Evaluating steps:
##[debug]........=> Object
##[debug]........Evaluating String:
##[debug]........=> 'create-test-resource-group'
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'outputs'
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'rg_name'
##[debug]..=> 'rg-a03577e-test-we-001'
##[debug]..Evaluating Index:
##[debug]....Evaluating secrets:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'AZURE_TENANT_ID'
##[debug]..=> '***'
##[debug]..Evaluating Index:
##[debug]....Evaluating secrets:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'AZURE_CLIENT_ID_BRM_DEPLOYMENT_TEST_RG_003'
##[debug]..=> '***'
##[debug]..Evaluating Index:
##[debug]....Evaluating secrets:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'AZURE_CLIENT_SECRET_BRM_DEPLOYMENT_TEST_RG_003'
##[debug]..=> '***'
##[debug]=> 'docker run -v $(pwd)/modules:/app/modules thecloudtheory/azure-cost-estimator:latest modules\containerregistry\registries\test\main.test.bicep *** rg-a03577e-test-we-001 -e AZURE_TENANT_ID=*** -e AZURE_CLIENT_ID=*** -e AZURE_CLIENT_SECRET=***'
##[debug]Result: 'docker run -v $(pwd)/modules:/app/modules thecloudtheory/azure-cost-estimator:latest modules\containerregistry\registries\test\main.test.bicep *** rg-a03577e-test-we-001 -e AZURE_TENANT_ID=*** -e AZURE_CLIENT_ID=*** -e AZURE_CLIENT_SECRET=***'
##[debug]Loading env
Run docker run -v $(pwd)/modules:/app/modules thecloudtheory/azure-cost-estimator:latest modules\containerregistry\registries\test\main.test.bicep *** rg-a03577e-test-we-001 -e AZURE_TENANT_ID=*** -e AZURE_CLIENT_ID=*** -e AZURE_CLIENT_SECRET=***
##[debug]C:\Program Files\PowerShell\7\pwsh.EXE -command ". 'D:\a\_temp\1c32cb53-e37[6](https://github.com/xxx/bicep-registry-modules-test/actions/runs/6732626593/job/18299980260#step:8:6)-4fc0-9bf6-[7](https://github.com/xxx/bicep-registry-modules-test/actions/runs/6732626593/job/18299980260#step:8:7)b33[22](https://github.com/xxx/bicep-registry-modules-test/actions/runs/6732626593/job/18299980260#step:8:22)e[26](https://github.com/xxx/bicep-registry-modules-test/actions/runs/6732626593/job/18299980260#step:8:26)f00.ps1'"
docker: invalid reference format.
See 'docker run --help'.
Error: Process completed with exit code 1.
##[debug]Finishing: Cost estimate
```
Anything in particular that looks wrong here?

**Comment by kamil-mrzyglod** [comment] 2023-11-02 16:24
Hey, most likely the problem is the following section of your command:
```
docker run -v $(pwd)/modules:/app/modules
```

As you mentioned, that you're using Windows runner, are you sure the path returned by `pwd` doesn't contain spaces or whitespaces?

**Comment by BenjaminEngeset** [comment] 2023-11-09 12:31
> Hey, most likely the problem is the following section of your command:
> 
> ```
> docker run -v $(pwd)/modules:/app/modules
> ```
> 
> As you mentioned, that you're using Windows runner, are you sure the path returned by `pwd` doesn't contain spaces or whitespaces?

You are right, that was the mistake. Had to use `%cd%` instead.

However, I can tell that it's possible to use the reusable workflow created instead which would be more convenient.

Would it be possible to remove the requirement for the parameter `templateParamFile` and instead only pass in the template?

In many cases with Bicep there are no parameter file. Would it also be possible to make it support the Bicep format so I don't have to compile it to ARM JSON beforehand?

Example:

```
CostEstimate:
    uses: TheCloudTheory/arm-estimator/.github/workflows/estimateFromUrl.yml@main
    with:
      rg: 'MyResourceGroup'
      environment: '' #Use empty string for repo level secrets
      templateFileURL: https://raw.githubusercontent.com/xxx/xxx/main/modules/xxx/xxx/test/main.test.bicep
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
```

And at last, is it really necessary with the URL? As the reusable workflow runs locally in my repository as a job from my understanding it should also be possible to pass the file directly?

**Comment by kamil-mrzyglod** [comment] 2023-11-09 12:44
Hey, everything's possible, I just need to understand your use case :)

I believe it's not required to pass a file with parameters - do you see any specific error if you omit them?

Also - by Bicep format, do you mean https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/parameter-files?tabs=Bicep? If so, yeah, it'd possible, but I need to double check what's needed to leverage those. Let me come back to you shortly to see if I could incorporate that in upcoming 1.3, or you'd need to wait for 1.4 (preview).

**Comment by BenjaminEngeset** [comment] 2023-11-09 13:28
> Hey, everything's possible, I just need to understand your use case :)
> 
> I believe it's not required to pass a file with parameters - do you see any specific error if you omit them?
> 
> Also - by Bicep format, do you mean https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/parameter-files?tabs=Bicep? If so, yeah, it'd possible, but I need to double check what's needed to leverage those. Let me come back to you shortly to see if I could incorporate that in upcoming 1.3, or you'd need to wait for 1.4 (preview).

It's required, as it's declared as a parameter that needs a string as input. 

https://github.com/TheCloudTheory/arm-estimator/blob/618e76a7bc839d10bb8f5c47a5531c33425b52cf/.github/workflows/estimateFromUrl.yml#L26

Would it be sufficient enough to pass in an empty string as `''`?

What I mean by Bicep format is simply that instead of passing `main.json`  I'm instead passing in `main.bicep`  and that ACE would have to handle that scenario. Documentation is stating for now that it has has to be an URL with `.json` format.

![image](https://github.com/TheCloudTheory/arm-estimator/assets/99641908/2b7d9521-b992-4a1c-b49c-5e29207c1dd4)

 I'm not thinking about `.bicepparam`  right now, although it would be great to have support for that in the future, getting quite often used as `.json` parameter files can get quite complex easily.

**Comment by kamil-mrzyglod** [comment] 2023-11-09 13:44
So that's a typo in documentation :) You can pass your configuration written in Bicep since quite some time:
![image](https://github.com/TheCloudTheory/arm-estimator/assets/11725731/aea6ea8c-1e17-4443-9cd1-2052136e7f5d)

When using Docker, you don't need to install Azure CLI or Bicep as ACE's Docker image already contain Bicep CLI.

I misunderstood you regarding the workflow - for that I need to make some tests as the workflow itself wasn't create by myself. But definitely it shouldn't require parameteres and if so, I'll make appriopriate changes.

**Comment by BenjaminEngeset** [comment] 2023-11-10 12:00
> So that's a typo in documentation :) You can pass your configuration written in Bicep since quite some time: ![image](https://user-images.githubusercontent.com/11725731/281749098-aea6ea8c-1e17-4443-9cd1-2052136e7f5d.png)
> 
> When using Docker, you don't need to install Azure CLI or Bicep as ACE's Docker image already contains Bicep CLI.
> 
> I misunderstood you regarding the workflow - for that I need to make some tests as the workflow itself wasn't create by myself. But definitely it shouldn't require parameteres and if so, I'll make appriopriate changes.

Very nice! I'll do some testing myself. When passing `.bicep` to the reusable workflow I need a way to pass `AcrPull` identity to ACE, would it also be possible to add this? As a lot of the `.bicep` files themself references to a private Bicep container registry. We have discussed this earlier, but not with the reusable workflow.

**Comment by kamil-mrzyglod** [comment] 2023-11-12 06:54
@BenjaminEngeset The only thing you need to do is to make sure, that `ClientId` you're passing to the workflow has `AcrPull` assigned to it. From that perspective, it doesn't really matter if you use ACE directly or via workflow - authentication flow is the same.

**Comment by BenjaminEngeset** [comment] 2023-11-12 10:19
> @BenjaminEngeset The only thing you need to do is to make sure, that `ClientId` you're passing to the workflow has `AcrPull` assigned to it. From that perspective, it doesn't really matter if you use ACE directly or via workflow - authentication flow is the same.

Great, exactly what I was hoping for!

I have been testing the reusable workflow and the required keyword used for the parameter file doesn't accept an empty strig as input. That results in a terminating error.

**Comment by kamil-mrzyglod** [comment] 2023-11-13 11:31
I'll try to introduce a fix soon.

**Comment by kamil-mrzyglod** [comment] 2023-11-15 12:27
Closing in favour of #218 and #223

**Closed by kamil-mrzyglod** 2023-11-15 12:27 UTC
Labels: question
